services:
  bot:
    image: fadilaltunkaynak/botsystem:local
    build:
      context: ..
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    volumes:
      - bot-config:/config
    command: ["python", "-u", "galaxyscore.py", "-d", "/config"]

volumes:
  bot-config:
